services:
  app:
    build: .
    container_name: springboot_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/my_database?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user_password
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s
    networks:
      - ascend-network

  app-test:
    image: eclipse-temurin:17-jdk-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/my_database?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user_password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ascend-network

  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puser_password" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ascend-network

networks:
  ascend-network:
    driver: bridge